# Generated by Django 5.2.8 on 2025-12-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genre_movie_genres_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('can_moderate_reviews', 'Може модерувати відгуки')]},
        ),
    ]
